### ISSUE TITLE
Compatibility with Apple iOS (iPad)

### ISSUE THREAD

**Issue by svanimisetti** [stanoba/MIDI2Neopixel#1]
Thanks for sharing a great project. This is more of a question than an issue. Does this work with Apple devices? I have an iPad handy - which has Synthesia installed. Is it possible to upload/flash the firmware from Windows 10 into Pro Micro - and have it be recognized as a MIDI device from iPad? I don't think I will be able to connect the Pro Micro directly to the iPad - is there a converter or adapter required?

**Comment by stanoba** [comment]
Hi @svanimisetti, I think it could work. Check issues in **MIDIUSB** library used in this project https://github.com/arduino-libraries/MIDIUSB/issues?q=is%3Aissue+ipad

There is also working MIDIUSB library example https://github.com/fab672000/MIDIUSB_1x1, which mentions in the code:
```
 *   Important Note: needs D_CONFIG macro in USBCore.h to be patched to change USB_CONFIG_POWER_MA(500) 
 *     with a lower value (i.e 20) in order to work with iPad, as it is bus powered by the tablet.
```
Sorry, I'm not able to test it as I don't have iPhone, neither iPad.

**Comment by svanimisetti** [comment]
Thanks @stanoba - I did not realize there is a configuration parameter. I agree - it seems to be a hardware issue. I am using a very old iPad for testing (its stuck on iOS 9!). Also, using a lightning-USB adapter I bought from Amazon. It might be that this is a fake or MFi-based clone. I will try to exchange that with a genuine apple accessory and see if I have any luck. I will report findings here.

**Comment by svanimisetti** [comment]
Closing this issue - as multiple attempts did not resolve. I found that the issue is related to a faulty lightning-USB adapter. The first one I got was a clone and perhaps faulty. Replaced that with another one - but it now complains saying that ProMicro consumes too much power. This means I have to spend another 20$ to get the powered lighting-USB. For this kind of money just for an adapter, I am better of sticking to simpler solutions.

**Comment by stanoba** [comment]
Maybe you can try to patch `USBCore.h` in Arduino IDE (C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino) as mentioned above. On line 101 change `USB_CONFIG_POWER` from `500` to `20`. Compile code again and upload to ProMicro.
You can also add `#define USB_CONFIG_POWER  20` to top part of the `MIDI2Neopixel.ino` source file.
